# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afc6862d1d39a3d8ae1b12789922bb3d910afb6863fb6611d97a8e8b8564cb4f0fc74c4fa474c59911a71c51318211c69b5b0f7e5cdde2c790517b0dc920815b

test:
  secret_key_base: 3948211179ff00808c21df0896b2e80223c0df441c8d9872dc500e63efbbae73caa487c12bd98a6a75e62b3331cea67ad4a6ffed8a3f56129116e4488dd5818d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
